name: Node.js CI

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:


permissions:
  contents: read

jobs:

  test-node:

    name: Tests

    runs-on: [self-hosted, hardhat, hethers, standard, ephemeral]

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: cp .env-template .env

      - name: Build TypeScript
        run: npm run build

      - name: Install Docker Compose
        run: |
          sudo curl -SL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start the local node
        run: npx hedera restart --limits=false --dev=true -d

      - name: Run tests
        run: npm run test

      - name: Stop the local node
        run: npx hedera stop
